name: xplayer
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  chewie: ^1.7.5
  device_info_plus: ^11.2.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  http: ^1.2.0
  open_filex: ^4.5.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  m3u_parser_nullsafe: ^1.0.3
  package_info_plus: ^8.1.2
  path: ^1.8.3
  path_provider: ^2.1.4
  provider: ^6.1.2
  screenshot: ^3.0.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.2
  sqflite_common: ^2.5.4+6
  sqflite_common_ffi: ^2.3.4+4
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  video_player_win: ^3.1.1
  xml: ^6.5.0
  bonsoir: ^5.1.11
  web_socket_channel: ^2.4.0
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

dependency_overrides:
    video_player_android: 2.7.17

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
